### ISSUE TITLE
[Bug] SMAPI warning when warping to desert

### ISSUE THREAD

**Issue by NightFright2k19** [Floogen/DynamicReflections#19]
I got this SMAPI console warning when entering the desert with v1.3.0. This might have happened when I used the [Skull Cavern Elevator](https://www.nexusmods.com/stardewvalley/mods/963) (mod) or before, it might also not be related to that at all.

```
[Dynamic Reflections] This mod failed in the Player.Warped event. Technical details:
System.Collections.Generic.KeyNotFoundException: The given key 'StardewValley.Locations.Desert' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at DynamicReflections.Framework.Managers.PuddleManager.IsTilePuddle(GameLocation location, Int32 x, Int32 y) in C:\Users\Floogen\Documents\GitHub Repos\DynamicReflections\DynamicReflections\Framework\Managers\PuddleManager.cs:line 227
   at DynamicReflections.Framework.Managers.SkyManager.GeneratePerTile(GameLocation location) in C:\Users\Floogen\Documents\GitHub Repos\DynamicReflections\DynamicReflections\Framework\Managers\SkyManager.cs:line 63
   at DynamicReflections.Framework.Managers.SkyManager.Generate(GameLocation location, Boolean force) in C:\Users\Floogen\Documents\GitHub Repos\DynamicReflections\DynamicReflections\Framework\Managers\SkyManager.cs:line 47
   at DynamicReflections.DynamicReflections.OnWarped(Object sender, WarpedEventArgs e) in C:\Users\Floogen\Documents\GitHub Repos\DynamicReflections\DynamicReflections\DynamicReflections.cs:line 225
   at StardewModdingAPI.Framework.Events.ManagedEvent`1.Raise(TEventArgs args) in SMAPI\Framework\Events\ManagedEvent.cs:line 101
```

**Comment by NightFright2k19** [comment]
Found the trigger. Happens when warping to the desert with a totem, so it's (probably) not related to any other mod I have installed.
